// tests/perf/load_test.js
// k6 performance test for POST /tickets (Create a Ticket) 
// Run: node tests/perf/mock-server.js    (starts fake backend on http://localhost:4000)
// k6 run tests/perf/load_test.js -e API_BASE_URL=http://localhost:4000
// This targets tests/perf/mock-server.js: the real, unmodified tickets.routes.js router,
// running on a real Express server so k6 exercises real HTTP/routing/middleware overhead but with the Supabase layer swapped for in-memory fakes

import http from "k6/http";
import { check, sleep } from "k6";

export const options = {
  vus: 20, // Simulate 20 concurrent Virtual Users
  duration: "30s",

  // Threshold: 95% of requests must complete under 500ms
  // If this threshold is breached, k6 exits with a non-zero status code, useful for CI pipelines that should fail the build on a perf regression
  thresholds: {
    http_req_duration: ["p(95)<500"],
    checks: ["rate>0.95"], // at least 95% of checks (successful ticket creation) must pass
  },
};

const BASE_URL = __ENV.API_BASE_URL || "http://localhost:4000";

export default function () {
  const payload = JSON.stringify({
    category: "delivery",
    subject: `Load test ticket VU${__VU}-iter${__ITER}`,
    description: "Automatically generated by k6 for performance testing.",
  });

  const res = http.post(`${BASE_URL}/api/tickets`, payload, {
    headers: {
      "Content-Type": "application/json",
      // The mock server never actually validates this token, included only so the request shape matches what a real client sends
      Authorization: "Bearer fake-jwt",
    },
  });

  // Check: verify each response is actually a successful ticket creation, not just fast
  check(res, {
    "status is 201": (r) => r.status === 201,
    "response has success:true": (r) => {
      try {
        return JSON.parse(r.body).success === true;
      } catch {
        return false;
      }
    },
    "response has ticket.ticket_number": (r) => {
      try {
        return JSON.parse(r.body).ticket?.ticket_number !== undefined;
      } catch {
        return false;
      }
    },
  });

  sleep(1); // pace requests to mimic realistic user behavior between calls
}















// import http from "k6/http";
// import { check, sleep } from "k6";

// export const options = {
//   vus: 20,  // Simulate 20 concurrent Virtual Users
//   duration: "30s",

//   // Threshold: 95% of requests must complete under 500ms
//   // If this threshold is breached, k6 exits with a non-zero status code, useful for CI pipelines that should fail the build on a perf regression
//   thresholds: {
//     http_req_duration: ["p(95)<500"],
//     checks: ["rate>0.95"], // at least 95% of checks (status 200) must pass
//   },
// };

// const BASE_URL = "http://localhost:3000";

// export default function () {
//   const res = http.get(`${BASE_URL}/api/menu`);

//   // Check: verify each response is actually successful, not just fast
//   check(res, {
//     "status is 200": (r) => r.status === 200,
//     "response has categories": (r) => JSON.parse(r.body).categories !== undefined,
//     "response has items": (r) => JSON.parse(r.body).items !== undefined,
//   });

//   sleep(1); // pace requests to mimic realistic user behavior between calls
// }